version: "3"
services:
  server:
    image: wilsonzhong/earn_money_backend:latest
    container_name: earn_money_backend
    environment:
      HOST: mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    volumes:
      - ~/public:/app/public
  mysql:
    image: wilsonzhong/earn_money_sql:latest
    environment:
      MYSQL_ROOT_PASSWORD: EarnMoney
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/mysql:/var/lib/mysql